language: generic
sudo: required
services:
  - docker

before_install:
  -docker build -t cristiancamilo98/docker-udemy -f Dockerfile.dev .

script:
  - docker run -e CI=true USERNAME/docker-udemy npm run test
